
server:
  port: 8080

spring:
  application:
    name: 'pix'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: QrCode
      collection: pix

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
